# Generated by Django 2.1 on 2021-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('father_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('date_birthday', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Диагноз')),
                ('dosage', models.TextField(verbose_name='МНН Дозировка')),
                ('therapy', models.TextField(verbose_name='Схема лечения')),
                ('monthly_need', models.TextField(verbose_name='Месячная потребность')),
                ('annual_need', models.TextField(verbose_name='Годовая потребность')),
                ('type_register', models.CharField(choices=[(1, 'Регистр больных детей, страдающих гемофилией, болезнью Вилльбранда и другими наследственными коагулопатиями'), (2, 'Регистр больных детей, страдающих тромбоцитопенией и тромбоцитопатией'), (3, 'Регистр больных детей, страдающих наследственной анемией'), (4, 'Регистр больных детей, страдающих приобретенной апластической анемией')], max_length=255, verbose_name='Тип регистра')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=15, verbose_name='Пароль')),
                ('user_name', models.CharField(max_length=60, verbose_name='ФИО пользователя')),
                ('position', models.CharField(blank=True, max_length=70, null=True, verbose_name='Должность')),
                ('access', models.CharField(choices=[(1, 'Редактировать, добавлять и просматривать'), (2, 'Добавлять и просматривать'), (3, 'Только просматривать')], default=2, max_length=50, verbose_name='Уровень доступа')),
            ],
        ),
    ]
