# Generated by Django 2.1 on 2021-04-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_editor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registr.User', verbose_name='Последнее изменение'),
        ),
    ]
